# Zhenbang Xiao
# Hello World

include $(GNUSTEP_MAKEFILES)/common.make

# Project Name
TOOL_NAME = CardGame

# Included source files
CardGame_OBJC_FILES = Card.m

# Included header files
CardGame_HEADER_FILES = Card.h

# Compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import

# Compile rules
include $(GNUSTEP_MAKEFILES)/tool.make

