# Zhenbang Xiao
# Card Game from Stanford University Public Module CS192p

include $(GNUSTEP_MAKEFILES)/common.make

# Project Name
TOOL_NAME = CardGame

# Included source files
CardGame_OBJC_FILES = Card.m
CardGame_OBJC_FILES = Deck.m

# Included header files
CardGame_HEADER_FILES = Card.h
CardGame_HEADER_FILES = Deck.h

# Compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import

# Compile rules
include $(GNUSTEP_MAKEFILES)/tool.make

