# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase', '>= 2.4.1'
target 'OAuth Example' do

end

target 'OAuth ExampleTests' do

end

target 'OAuth ExampleUITests' do

end

