# Zhenbang Xiao
# Hello World

include $(GNUSTEP_MAKEFILES)/common.make

# Project Name
TOOL_NAME = HelloWorld

# Included source files
HelloWorld_OBJC_FILES = main.m

# Included header files
# HelloWorld_HEADER_FILES = XXX.h

# Compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import

# Compile rules
include $(GNUSTEP_MAKEFILES)/tool.make

