# Zhenbang Xiao
# Loop

include $(GNUSTEP_MAKEFILES)/common.make

# Project Name
TOOL_NAME = Loop

# Included source files
Loop_OBJC_FILES = main.m

# Included header files
# Loop_HEADER_FILES = XXX.h

# Compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import -std=c99

# Compile rules
include $(GNUSTEP_MAKEFILES)/tool.make

