# Zhenbang Xiao
# Exchange Value of Variables

include $(GNUSTEP_MAKEFILES)/common.make

# Project Name
TOOL_NAME = ExchangeVar

# Included source files
ExchangeVar_OBJC_FILES = main.m

# Included header files
# ExchangeVar_HEADER_FILES = XXX.h

# Compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import

# Compile rules
include $(GNUSTEP_MAKEFILES)/tool.make